# Generated by Django 5.2.11 on 2026-02-17 18:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/%Y/%m/', verbose_name='Imagem')),
                ('principal', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
            ],
            options={
                'verbose_name': 'Imagem de Produto',
                'verbose_name_plural': 'Imagens de Produtos',
                'ordering': ['produto', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras (EAN/UPC)')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU (Código Único)')),
                ('ncm', models.CharField(blank=True, help_text='Nomenclatura Comum do Mercosul', max_length=10, null=True, verbose_name='NCM')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('fabricante', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fabricante')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('PC', 'Peça'), ('PAR', 'Par'), ('DZ', 'Dúzia')], default='UN', max_length=10, verbose_name='Unidade de Medida')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura (cm)')),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Largura (cm)')),
                ('profundidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Profundidade (cm)')),
            ],
            options={
                'verbose_name': 'Atributos do Produto',
                'verbose_name_plural': 'Atributos dos Produtos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Categoria Ativa')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='estoque.categoriaproduto', verbose_name='Categoria Pai')),
                ('usuario_criacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.IntegerField(help_text='Quantidade de itens movimentados', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor unitário do produto nesta movimentação', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitário')),
                ('observacao', models.TextField(blank=True, help_text='Informações adicionais sobre a movimentação', null=True, verbose_name='Observação')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('usuario', models.ForeignKey(default=1, help_text='Usuário que realizou a movimentação', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do produto', max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do produto (opcional)', null=True, verbose_name='Descrição')),
                ('preco_custo', models.DecimalField(decimal_places=2, help_text='Valor pago pelo produto (custo de aquisição)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, help_text='Valor de venda do produto ao cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Venda')),
                ('estoque_atual', models.IntegerField(default=0, help_text='Quantidade disponível em estoque', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Atual')),
                ('estoque_minimo', models.IntegerField(default=10, help_text='Quantidade mínima para alerta de reposição', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Mínimo')),
                ('estoque_maximo', models.IntegerField(default=100, help_text='Quantidade máxima recomendada em estoque', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Máximo')),
                ('sku', models.CharField(blank=True, help_text='Código único para identificação do produto na empresa', max_length=100, null=True, verbose_name='SKU (Código Interno)')),
                ('ncm', models.CharField(blank=True, help_text='Código NCM com 8 dígitos. Ex: 12345678 - Obrigatório para NF-e', max_length=10, null=True, verbose_name='NCM (Nomenclatura Comum do Mercosul)')),
                ('cest', models.CharField(blank=True, help_text='Código CEST com 7 dígitos (opcional). Ex: 1234567', max_length=7, null=True, verbose_name='CEST (Código Especificador da Substituição Tributária)')),
                ('ean_gtin', models.CharField(blank=True, help_text='Código de barras EAN-13 ou EAN-14 com dígito verificador', max_length=14, null=True, unique=True, verbose_name='EAN/GTIN (Código de Barras)')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Peso do produto em quilogramas (para cálculo de frete)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso (kg)')),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Altura do produto em centímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura (cm)')),
                ('largura_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Largura do produto em centímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Largura (cm)')),
                ('profundidade_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Profundidade do produto em centímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Profundidade (cm)')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=6, help_text='Volume do produto em metros cúbicos (calculado automaticamente)', max_digits=10, null=True, verbose_name='Volume (m3)')),
                ('localizacao_estoque', models.CharField(blank=True, help_text='Ex: Corredor A, Estante 2, Prateleira 3, Caixa 5', max_length=100, null=True, verbose_name='Localização no Estoque')),
                ('categoria', models.CharField(blank=True, help_text='Ex: Eletrônicos, Vestuário, Alimentos', max_length=100, null=True, verbose_name='Categoria do Produto')),
                ('subcategoria', models.CharField(blank=True, help_text='Ex: Notebooks, Camisetas, Bebidas', max_length=100, null=True, verbose_name='Subcategoria')),
                ('marca', models.CharField(blank=True, help_text='Marca ou fabricante do produto', max_length=100, null=True, verbose_name='Marca do Produto')),
                ('icms_aliquota', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de ICMS aplicável (ex: 18.00)', max_digits=5, verbose_name='Alíquota ICMS (%)')),
                ('ipi_aliquota', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de IPI aplicável (ex: 15.00)', max_digits=5, verbose_name='Alíquota IPI (%)')),
                ('pis_aliquota', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de PIS aplicável', max_digits=5, verbose_name='Alíquota PIS (%)')),
                ('cofins_aliquota', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de COFINS aplicável', max_digits=5, verbose_name='Alíquota COFINS (%)')),
                ('imagem', models.ImageField(blank=True, help_text='Foto do produto para o catálogo de vendedores', null=True, upload_to='produtos/', verbose_name='Imagem do Produto')),
                ('visivel_catalogo', models.BooleanField(default=True, help_text='Se marcado, o produto aparecerá no catálogo para consulta de vendedores', verbose_name='Visível no Catálogo de Vendedores')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o produto está disponível para movimentação', verbose_name='Produto Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
