# Generated by Django 5.2.11 on 2026-02-06 04:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'ordering': ['-data_movimentacao'], 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='observacao',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre a movimentação', null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuário que realizou a movimentação', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.01, help_text='Valor unitário do produto nesta movimentação', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Unitário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o produto está disponível para movimentação', verbose_name='Produto Ativo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Modificação'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=10, help_text='Quantidade mínima para alerta de reposição', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Mínimo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='usuario_criacao',
            field=models.ForeignKey(default=1, help_text='Usuário que cadastrou o produto', on_delete=django.db.models.deletion.PROTECT, related_name='produtos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='produto',
            name='usuario_modificacao',
            field=models.ForeignKey(blank=True, help_text='Último usuário que modificou o produto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.IntegerField(help_text='Quantidade de itens movimentados', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do produto (opcional)', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_atual',
            field=models.IntegerField(default=0, help_text='Quantidade disponível em estoque', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Atual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Nome completo do produto', max_length=200, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, help_text='Valor pago pelo produto (custo de aquisição)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, help_text='Valor de venda do produto ao cliente', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço de Venda'),
        ),
    ]
