# Generated by Django 5.2.11 on 2026-02-17 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Fornecedor padrão para reposição de estoque', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='fornecedores.fornecedor', verbose_name='Fornecedor Principal'),
        ),
        migrations.AddField(
            model_name='produto',
            name='usuario_criacao',
            field=models.ForeignKey(default=1, help_text='Usuário que cadastrou o produto', on_delete=django.db.models.deletion.PROTECT, related_name='produtos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='produto',
            name='usuario_modificacao',
            field=models.ForeignKey(blank=True, help_text='Último usuário que modificou o produto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='produtoatributo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.categoriaproduto', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='produtoatributo',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='estoque.produto', verbose_name='Produto'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['company', 'sku'], name='estoque_pro_company_8c32e5_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ncm'], name='estoque_pro_ncm_39b703_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ean_gtin'], name='estoque_pro_ean_gti_61705b_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria'], name='estoque_pro_categor_68c530_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['visivel_catalogo', 'ativo'], name='estoque_pro_visivel_d5af44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('company', 'sku')},
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', '-data_movimentacao'], name='estoque_mov_produto_345496_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo', '-data_movimentacao'], name='estoque_mov_tipo_6019ee_idx'),
        ),
    ]
