# Generated by Django 5.2.11 on 2026-02-06 06:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_movimentacaoestoque_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, verbose_name='Categoria Ativa')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='estoque.categoriaproduto', verbose_name='Categoria Pai')),
                ('usuario_criacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/%Y/%m/', verbose_name='Imagem')),
                ('principal', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem de Produto',
                'verbose_name_plural': 'Imagens de Produtos',
                'ordering': ['produto', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras (EAN/UPC)')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU (Código Único)')),
                ('ncm', models.CharField(blank=True, help_text='Nomenclatura Comum do Mercosul', max_length=10, null=True, verbose_name='NCM')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('fabricante', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fabricante')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('CX', 'Caixa'), ('PC', 'Peça'), ('PAR', 'Par'), ('DZ', 'Dúzia')], default='UN', max_length=10, verbose_name='Unidade de Medida')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura (cm)')),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Largura (cm)')),
                ('profundidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Profundidade (cm)')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.categoriaproduto', verbose_name='Categoria')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Atributos do Produto',
                'verbose_name_plural': 'Atributos dos Produtos',
            },
        ),
    ]
