# Generated by Django 5.2.9 on 2026-02-08 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_categoriaproduto_imagemproduto_produtoatributo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ean_gtin',
            field=models.CharField(blank=True, help_text='Codigo de barras EAN-13 ou EAN-14', max_length=14, null=True, unique=True, verbose_name='EAN/GTIN'),
        ),
        migrations.AddField(
            model_name='produto',
            name='localizacao_estoque',
            field=models.CharField(blank=True, help_text='Ex: Corredor A, Estante 2, Prateleira 3', max_length=50, null=True, verbose_name='Localizacao no Estoque'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, help_text='Nomenclatura Comum do Mercosul', max_length=10, null=True, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, help_text='Codigo unico para identificacao do produto', max_length=100, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o produto esta disponivel para movimentacao', verbose_name='Produto Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=10, help_text='Quantidade minima para alerta de reposicao', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Minimo'),
        ),
    ]
