# Generated by Django 5.2.9 on 2026-02-08 03:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_produto_ean_gtin_produto_localizacao_estoque_and_more'),
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='altura_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura do produto em centímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ex: Eletrônicos, Vestuário, Alimentos', max_length=100, null=True, verbose_name='Categoria do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cest',
            field=models.CharField(blank=True, help_text='Código CEST com 7 dígitos (opcional). Ex: 1234567', max_length=7, null=True, verbose_name='CEST (Código Especificador da Substituição Tributária)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cofins_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de COFINS aplicável', max_digits=5, verbose_name='Alíquota COFINS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_maximo',
            field=models.IntegerField(default=100, help_text='Quantidade máxima recomendada em estoque', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Máximo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Fornecedor padrão para reposição de estoque', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='fornecedores.fornecedor', verbose_name='Fornecedor Principal'),
        ),
        migrations.AddField(
            model_name='produto',
            name='icms_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de ICMS aplicável (ex: 18.00)', max_digits=5, verbose_name='Alíquota ICMS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Foto do produto para o catálogo de vendedores', null=True, upload_to='produtos/', verbose_name='Imagem do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ipi_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de IPI aplicável (ex: 15.00)', max_digits=5, verbose_name='Alíquota IPI (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largura do produto em centímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Largura (cm)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca ou fabricante do produto', max_length=100, null=True, verbose_name='Marca do Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso do produto em quilogramas (para cálculo de frete)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pis_aliquota',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de PIS aplicável', max_digits=5, verbose_name='Alíquota PIS (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='profundidade_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profundidade do produto em centímetros', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Profundidade (cm)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.CharField(blank=True, help_text='Ex: Notebooks, Camisetas, Bebidas', max_length=100, null=True, verbose_name='Subcategoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='visivel_catalogo',
            field=models.BooleanField(default=True, help_text='Se marcado, o produto aparecerá no catálogo para consulta de vendedores', verbose_name='Visível no Catálogo de Vendedores'),
        ),
        migrations.AddField(
            model_name='produto',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Volume do produto em metros cúbicos (calculado automaticamente)', max_digits=10, null=True, verbose_name='Volume (m³)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se o produto está disponível para movimentação', verbose_name='Produto Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ean_gtin',
            field=models.CharField(blank=True, help_text='Código de barras EAN-13 ou EAN-14 com dígito verificador', max_length=14, null=True, unique=True, verbose_name='EAN/GTIN (Código de Barras)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.IntegerField(default=10, help_text='Quantidade mínima para alerta de reposição', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque Mínimo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='localizacao_estoque',
            field=models.CharField(blank=True, help_text='Ex: Corredor A, Estante 2, Prateleira 3, Caixa 5', max_length=100, null=True, verbose_name='Localização no Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, help_text='Código NCM com 8 dígitos. Ex: 12345678 - Obrigatório para NF-e', max_length=10, null=True, verbose_name='NCM (Nomenclatura Comum do Mercosul)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único para identificação do produto na empresa', max_length=100, null=True, unique=True, verbose_name='SKU (Código Interno)'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', '-data_movimentacao'], name='estoque_mov_produto_345496_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['tipo', '-data_movimentacao'], name='estoque_mov_tipo_6019ee_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['sku'], name='estoque_pro_sku_a5fad6_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ncm'], name='estoque_pro_ncm_39b703_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ean_gtin'], name='estoque_pro_ean_gti_61705b_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria'], name='estoque_pro_categor_68c530_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['visivel_catalogo', 'ativo'], name='estoque_pro_visivel_d5af44_idx'),
        ),
    ]
