# Generated by Django 5.2.11 on 2026-02-17 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('estoque', '0005_produto_altura_cm_produto_categoria_produto_cest_and_more'),
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='produto',
            name='estoque_pro_sku_a5fad6_idx',
        ),
        migrations.AddField(
            model_name='produto',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa proprietária deste produto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Volume do produto em metros cúbicos (calculado automaticamente)', max_digits=10, null=True, verbose_name='Volume (m3)'),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('company', 'sku')},
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['company', 'sku'], name='estoque_pro_company_8c32e5_idx'),
        ),
    ]
