# Generated by Django 5.2.11 on 2026-02-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_produto_estoque_pro_sku_a5fad6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, help_text='Código único para identificação do produto na empresa', max_length=100, null=True, verbose_name='SKU (Código Interno)'),
        ),
    ]
