# Generated by Django 5.2.9 on 2026-02-08 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcessoDadosSensiveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dado', models.CharField(choices=[('CPF', 'CPF/CNPJ'), ('EMAIL', 'Email'), ('TELEFONE', 'Telefone'), ('ENDERECO', 'Endereco'), ('DADOS_COMPLETOS', 'Todos os Dados Pessoais'), ('HISTORICO_VENDAS', 'Historico de Vendas'), ('HISTORICO_PAGAMENTOS', 'Historico de Pagamentos')], max_length=50, verbose_name='Tipo de Dado Acessado')),
                ('cliente_id', models.PositiveIntegerField(verbose_name='ID do Cliente')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('motivo', models.CharField(blank=True, help_text='Ex: Consulta de Venda, Emissao de Nota Fiscal', max_length=255, verbose_name='Motivo do Acesso')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereco IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent do Navegador')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Acesso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acessos_dados_sensiveis', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Acesso a Dados Sensiveis',
                'verbose_name_plural': 'Logs de Acesso a Dados Sensiveis',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['usuario', '-data_hora'], name='auditoria_l_usuario_4a07d7_idx'), models.Index(fields=['cliente_id', '-data_hora'], name='auditoria_l_cliente_70bc9f_idx'), models.Index(fields=['tipo_dado', '-data_hora'], name='auditoria_l_tipo_da_7b0748_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CRIAR', 'Criacao'), ('ATUALIZAR', 'Atualizacao'), ('DELETAR', 'Delecao'), ('VISUALIZAR', 'Visualizacao'), ('EXPORTAR', 'Exportacao'), ('ANONIMIZAR', 'Anonimizacao')], max_length=20, verbose_name='Tipo de Acao')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID do Objeto')),
                ('valores_anteriores', models.JSONField(blank=True, help_text='JSON com os valores antes da alteracao', null=True, verbose_name='Valores Anteriores')),
                ('valores_novos', models.JSONField(blank=True, help_text='JSON com os valores apos a alteracao', null=True, verbose_name='Valores Novos')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao da Acao')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereco IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent do Navegador')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Modelo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acoes_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['usuario', '-data_hora'], name='auditoria_l_usuario_40b4c8_idx'), models.Index(fields=['tipo_acao', '-data_hora'], name='auditoria_l_tipo_ac_1468d1_idx'), models.Index(fields=['content_type', 'object_id'], name='auditoria_l_content_9b61b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.PositiveIntegerField(verbose_name='ID do Cliente')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('tipo_solicitacao', models.CharField(choices=[('ACESSO', 'Acesso aos Dados'), ('CORRECAO', 'Correcao de Dados'), ('DELECAO', 'Delecao de Dados'), ('PORTABILIDADE', 'Portabilidade de Dados'), ('OPOSICAO', 'Oposicao ao Processamento')], max_length=20, verbose_name='Tipo de Solicitacao')),
                ('descricao', models.TextField(verbose_name='Descricao da Solicitacao')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROCESSAMENTO', 'Em Processamento'), ('CONCLUIDA', 'Concluida'), ('RECUSADA', 'Recusada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitacao')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conclusao')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta ou Motivo da Recusa')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_lgpd_processadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsavel')),
            ],
            options={
                'verbose_name': 'Solicitacao LGPD',
                'verbose_name_plural': 'Solicitacoes LGPD',
                'ordering': ['-data_solicitacao'],
                'indexes': [models.Index(fields=['cliente_id', '-data_solicitacao'], name='auditoria_s_cliente_612a33_idx'), models.Index(fields=['status', '-data_solicitacao'], name='auditoria_s_status_435035_idx')],
            },
        ),
    ]
