# Generated by Django 5.2.11 on 2026-02-17 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fornecedor',
            name='fornecedore_nome_7e1ed0_idx',
        ),
        migrations.RemoveIndex(
            model_name='fornecedor',
            name='fornecedore_email_36b22a_idx',
        ),
        migrations.RemoveIndex(
            model_name='fornecedor',
            name='fornecedore_cnpj_a9fb5e_idx',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_app', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together={('company', 'cnpj'), ('company', 'email')},
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['company', 'nome', 'ativo'], name='fornecedore_company_f41982_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['company', 'email'], name='fornecedore_company_f1d1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['company', 'cnpj'], name='fornecedore_company_564967_idx'),
        ),
    ]
