# Generated by Django 5.2.11 on 2026-02-06 04:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0002_alter_movimentacaoestoque_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(help_text='Razão social do fornecedor', max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, help_text='Nome fantasia do fornecedor', max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(help_text='CNPJ do fornecedor (formato: 00.000.000/0000-00)', max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('endereco', models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Fornecedor Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_criacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEletronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(help_text='Chave de acesso da NF-e (44 dígitos)', max_length=44, unique=True, verbose_name='Chave de Acesso')),
                ('numero', models.CharField(max_length=20, verbose_name='Número da NF-e')),
                ('serie', models.CharField(max_length=10, verbose_name='Série')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('valor_produtos', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor dos Produtos')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor ICMS')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor IPI')),
                ('valor_pis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor PIS')),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor COFINS')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor do Frete')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de Desconto')),
                ('natureza_operacao', models.CharField(max_length=100, verbose_name='Natureza da Operação')),
                ('cfop', models.CharField(help_text='Código Fiscal de Operações e Prestações', max_length=10, verbose_name='CFOP')),
                ('xml_arquivo', models.FileField(upload_to='nfe_xml/%Y/%m/', verbose_name='Arquivo XML')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Processamento'), ('PROCESSADA', 'Processada com Sucesso'), ('ERRO', 'Erro no Processamento'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='fiscal.fornecedor', verbose_name='Fornecedor')),
                ('usuario_importacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='nfes_importadas', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Nota Fiscal Eletrônica',
                'verbose_name_plural': 'Notas Fiscais Eletrônicas',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.IntegerField(verbose_name='Número do Item')),
                ('codigo_produto', models.CharField(max_length=100, verbose_name='Código do Produto')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('ncm', models.CharField(blank=True, max_length=10, null=True, verbose_name='NCM')),
                ('cfop', models.CharField(max_length=10, verbose_name='CFOP')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Total')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor de Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor do Frete')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor ICMS')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor IPI')),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Alíquota ICMS (%)')),
                ('aliquota_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Alíquota IPI (%)')),
                ('criado_automaticamente', models.BooleanField(default=False, help_text='Indica se o produto foi criado automaticamente durante a importação', verbose_name='Produto Criado Automaticamente')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nfe', to='estoque.produto', verbose_name='Produto Cadastrado')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.notafiscaleletronica', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Item de Nota Fiscal',
                'verbose_name_plural': 'Itens de Nota Fiscal',
                'ordering': ['nota_fiscal', 'numero_item'],
                'unique_together': {('nota_fiscal', 'numero_item')},
            },
        ),
    ]
