# Generated by Django 5.2.11 on 2026-02-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_produto_altura_cm_produto_categoria_produto_cest_and_more'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoFiscal',
            fields=[
            ],
            options={
                'verbose_name': 'Produto (Fiscal)',
                'verbose_name_plural': 'Produtos (Fiscal)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoque.produto',),
        ),
    ]
