# Generated by Django 5.2.11 on 2026-02-06 04:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primeiro dia do mês de referência', unique=True, verbose_name='Período')),
                ('total_receitas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de Receitas')),
                ('total_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total de Despesas')),
                ('lucro_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Lucro Bruto')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Indicador Financeiro',
                'verbose_name_plural': 'Indicadores Financeiros',
                'ordering': ['-periodo'],
            },
        ),
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={'ordering': ['-data'], 'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('COMPRA', 'Compra de Produtos'), ('SALARIO', 'Salários e Encargos'), ('ALUGUEL', 'Aluguel e Condomínio'), ('SERVICO', 'Serviços Contratados'), ('IMPOSTO', 'Impostos e Taxas'), ('OUTROS', 'Outros')], default='OUTROS', help_text='Categoria da despesa', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuário que registrou a despesa', on_delete=django.db.models.deletion.PROTECT, related_name='despesas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('VENDA', 'Venda de Produtos'), ('SERVICO', 'Prestação de Serviços'), ('INVESTIMENTO', 'Retorno de Investimento'), ('OUTROS', 'Outros')], default='VENDA', help_text='Categoria da receita', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='usuario',
            field=models.ForeignKey(default=1, help_text='Usuário que registrou a receita', on_delete=django.db.models.deletion.PROTECT, related_name='receitas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(help_text='Data em que a despesa foi realizada', verbose_name='Data da Despesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(help_text='Descrição detalhada da despesa', max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor da despesa em R$', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(help_text='Data em que a receita foi recebida', verbose_name='Data da Receita'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(help_text='Descrição detalhada da receita', max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Valor da receita em R$', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='CapitalGiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=2, help_text='Valor do capital antes da movimentação', max_digits=12, verbose_name='Valor Anterior')),
                ('valor_novo', models.DecimalField(decimal_places=2, help_text='Valor do capital após a movimentação', max_digits=12, verbose_name='Valor Novo')),
                ('tipo_movimentacao', models.CharField(choices=[('ENTRADA', 'Entrada de Capital'), ('SAIDA', 'Saída de Capital'), ('AJUSTE', 'Ajuste Manual')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('descricao', models.TextField(help_text='Descrição detalhada da movimentação', verbose_name='Descrição')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('usuario', models.ForeignKey(default=1, help_text='Usuário que realizou a movimentação', on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_capital', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Capital de Giro',
                'verbose_name_plural': 'Histórico de Capital de Giro',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
