# Generated by Django 5.2.11 on 2026-02-08 06:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_anonimizado_cliente_consentimento_dados_and_more'),
        ('financeiro', '0002_indicadorfinanceiro_alter_despesa_options_and_more'),
        ('fiscal', '0002_produtofiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='fiscal.fornecedor', verbose_name='Fornecedor')),
                ('usuario_criacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario_criacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='FluxoCaixaProjetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Mês 1'), (2, 'Mês 2'), (3, 'Mês 3'), (4, 'Mês 4'), (5, 'Mês 5'), (6, 'Mês 6'), (7, 'Mês 7'), (8, 'Mês 8'), (9, 'Mês 9'), (10, 'Mês 10'), (11, 'Mês 11'), (12, 'Mês 12')], verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('receitas_projetadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Receitas Projetadas')),
                ('despesas_projetadas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Despesas Projetadas')),
                ('receitas_reais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Receitas Reais')),
                ('despesas_reais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Despesas Reais')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Fluxo de Caixa Projetado',
                'verbose_name_plural': 'Fluxos de Caixa Projetados',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
    ]
