# Generated by Django 5.2.11 on 2026-02-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contapagar_contareceber_fluxocaixaprojetado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(help_text='Ex: Pagamento Aluguel Jan/2026, Compra de insumos, etc.', max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('VENDA', 'Venda de Produtos'), ('SERVICO', 'Prestação de Serviços'), ('INVESTIMENTO', 'Retorno de Investimento'), ('OUTROS', 'Outros')], default='VENDA', help_text='Classificação para relatórios financeiros e gráficos.', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(help_text='Ex: Venda de 10 camisetas, Pagamento serviço X, etc.', max_length=200, verbose_name='Descrição'),
        ),
    ]
