# Generated by Django 5.2.11 on 2026-02-17 18:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_clientes_cl_nome_0ac9fe_idx_and_more'),
        ('companies', '0001_initial'),
        ('financeiro', '0004_alter_despesa_descricao_alter_receita_categoria_and_more'),
        ('fornecedores', '0002_remove_fornecedor_fornecedore_nome_7e1ed0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitalgiro',
            options={'verbose_name': 'Movimentação de Capital', 'verbose_name_plural': 'Movimentações de Capital'},
        ),
        migrations.AlterModelOptions(
            name='contapagar',
            options={'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.AlterModelOptions(
            name='contareceber',
            options={'verbose_name': 'Conta a Receber', 'verbose_name_plural': 'Contas a Receber'},
        ),
        migrations.AlterModelOptions(
            name='fluxocaixaprojetado',
            options={'verbose_name': 'Fluxo de Caixa Projetado', 'verbose_name_plural': 'Fluxos de Caixa Projetados'},
        ),
        migrations.AlterModelOptions(
            name='indicadorfinanceiro',
            options={'verbose_name': 'Indicador Financeiro', 'verbose_name_plural': 'Indicadores Financeiros'},
        ),
        migrations.AlterUniqueTogether(
            name='fluxocaixaprojetado',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='capitalgiro',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_capital', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='fluxocaixaprojetado',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_caixa', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='indicadorfinanceiro',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='receita',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='capitalgiro',
            name='data_movimentacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='capitalgiro',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='capitalgiro',
            name='tipo_movimentacao',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='capitalgiro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='capitalgiro',
            name='valor_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='capitalgiro',
            name='valor_novo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='data_vencimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedor'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='usuario_criacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='data_vencimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='usuario_criacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('COMPRA', 'Compra de Mercadorias'), ('OPERACIONAL', 'Custos Operacionais'), ('SALARIO', 'Salários e Encargos'), ('IMPOSTO', 'Impostos e Taxas'), ('OUTROS', 'Outros')], default='COMPRA', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='fluxocaixaprojetado',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fluxocaixaprojetado',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fluxocaixaprojetado',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fluxocaixaprojetado',
            name='despesas_projetadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fluxocaixaprojetado',
            name='despesas_reais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fluxocaixaprojetado',
            name='mes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='fluxocaixaprojetado',
            name='receitas_projetadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fluxocaixaprojetado',
            name='receitas_reais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='indicadorfinanceiro',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='indicadorfinanceiro',
            name='lucro_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='indicadorfinanceiro',
            name='margem_lucro',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='indicadorfinanceiro',
            name='periodo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='indicadorfinanceiro',
            name='total_despesas',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='indicadorfinanceiro',
            name='total_receitas',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('VENDA', 'Venda de Produtos'), ('SERVICO', 'Prestação de Serviços'), ('INVESTIMENTO', 'Retorno de Investimento'), ('OUTROS', 'Outros')], default='VENDA', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(verbose_name='Data do Recebimento'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor'),
        ),
        migrations.AlterUniqueTogether(
            name='fluxocaixaprojetado',
            unique_together={('company', 'mes', 'ano')},
        ),
    ]
