# Generated by Django 5.2.11 on 2026-02-06 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('estoque', '0003_categoriaproduto_imagemproduto_produtoatributo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usuario_abertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL)),
                ('usuario_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'db_table': 'pdv_caixa',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('numero_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_itens', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CHEQUE', 'Cheque'), ('CREDITO_LOJA', 'Crédito em Loja')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='clientes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'pdv_venda',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_pdv', to='estoque.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pdv.venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
                'db_table': 'pdv_item_venda',
            },
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['-data_venda'], name='pdv_venda_data_ve_9747c6_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['usuario', '-data_venda'], name='pdv_venda_usuario_fc4a16_idx'),
        ),
    ]
