# Generated by Django 5.2.11 on 2026-02-17 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cpf_cnpj', models.CharField(db_index=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('consentimento_marketing', models.BooleanField(default=False, help_text='Cliente autorizou recebimento de comunicações comerciais', verbose_name='Consentimento para Marketing')),
                ('consentimento_dados', models.BooleanField(default=False, help_text='Cliente autorizou armazenamento e processamento de dados pessoais', verbose_name='Consentimento de Dados')),
                ('data_consentimento', models.DateTimeField(blank=True, help_text='Data em que o cliente deu consentimento', null=True, verbose_name='Data do Consentimento')),
                ('anonimizado', models.BooleanField(default=False, help_text='Indica se os dados pessoais foram removidos conforme LGPD', verbose_name='Dados Anonimizados')),
                ('data_anonimizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Anonimização')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='companies.company', verbose_name='Empresa')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_criados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes_cliente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TELEFONE', 'Telefone'), ('EMAIL', 'Email'), ('CELULAR', 'Celular'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('valor', models.CharField(max_length=100)),
                ('principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contato do Cliente',
                'verbose_name_plural': 'Contatos dos Clientes',
                'db_table': 'clientes_contato',
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['company', 'nome', 'ativo'], name='clientes_cl_company_236a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['company', 'email'], name='clientes_cl_company_e33df2_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['company', 'cpf_cnpj'], name='clientes_cl_company_a00cf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('company', 'cpf_cnpj'), ('company', 'email')},
        ),
    ]
