# Generated by Django 5.2.9 on 2026-02-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='anonimizado',
            field=models.BooleanField(default=False, help_text='Indica se os dados pessoais foram removidos conforme LGPD', verbose_name='Dados Anonimizados'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='consentimento_dados',
            field=models.BooleanField(default=False, help_text='Cliente autorizou armazenamento e processamento de dados pessoais', verbose_name='Consentimento de Dados'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='consentimento_marketing',
            field=models.BooleanField(default=False, help_text='Cliente autorizou recebimento de comunicações comerciais', verbose_name='Consentimento para Marketing'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_anonimizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Anonimização'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_consentimento',
            field=models.DateTimeField(blank=True, help_text='Data em que o cliente deu consentimento', null=True, verbose_name='Data do Consentimento'),
        ),
    ]
