# Generated by Django 5.2.11 on 2026-02-17 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_anonimizado_cliente_consentimento_dados_and_more'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_nome_0ac9fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_email_eae461_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_cpf_cnp_0eeb49_idx',
        ),
        migrations.AddField(
            model_name='cliente',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='companies.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('company', 'cpf_cnpj'), ('company', 'email')},
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['company', 'nome', 'ativo'], name='clientes_cl_company_236a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['company', 'email'], name='clientes_cl_company_e33df2_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['company', 'cpf_cnpj'], name='clientes_cl_company_a00cf5_idx'),
        ),
    ]
