# Generated by Django 5.2.11 on 2026-02-17 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ESTOQUE', 'Alerta de Estoque'), ('PEDIDO', 'Novo Pedido'), ('FINANCEIRO', 'Alerta Financeiro'), ('SISTEMA', 'Notificação do Sistema'), ('VENDA', 'Alerta de Venda')], max_length=20, verbose_name='Tipo de Notificação')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('url_acao', models.CharField(blank=True, help_text='URL para onde o usuário será redirecionado ao clicar na notificação', max_length=500, null=True, verbose_name='URL da Ação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['usuario', '-data_criacao'], name='notificacoe_usuario_1031fd_idx'), models.Index(fields=['usuario', 'lida'], name='notificacoe_usuario_a5894e_idx')],
            },
        ),
    ]
